### ISSUE TITLE
react native lyrics are not properly because active , autoScroll,currentTime is not work

### ISSUE THREAD

**Issue by codewithsujeet** [hoanganhken97/react-native-lyric#2]
const lineRenderer = useCallback(
    ({lrcLine: {millisecond, content}, index, active}) => (
      <Text style={{textAlign: 'center', color: active ? 'green' : 'grey'}}>
        {content}
      </Text>
    ),
    [],
  );

<Lyric
        style={{height: 500}}
        lrc={lrc}
        currentTime={0}
        lineHeight={16}
        lineRenderer={lineRenderer}
        onCurrentLineChange={onCurrentLineChange}
        autoScroll={true}
        activeLineHeight={16}

      />
![WhatsApp Image 2022-09-27 at 10 45 45 AM (1)](https://user-images.githubusercontent.com/89513698/192438058-7e11e837-e65e-45ad-b7e4-f9f9064eb018.jpeg)

Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'scrollToOffset' of null
TypeError: Cannot read property 'scrollToOffset' of null

**Comment by hoanganhken97** [comment]
Hi @codewithsujeet you can see the example here
https://snack.expo.dev/@hoanganhken/react-native-lyric-example-
